# Generated by Django 3.2.3 on 2024-12-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название ингредиента', max_length=255, unique=True, verbose_name='Название ингредиента')),
                ('unit', models.CharField(help_text='Введите единицу измерения', max_length=255, verbose_name='Единица измерения')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название рецепта', max_length=255, verbose_name='Название рецепта')),
                ('image', models.ImageField(help_text='Загрузите изображение рецепта', upload_to='recipes/', verbose_name='Картинка рецепта')),
                ('text', models.TextField(help_text='Введите описание рецепта', verbose_name='Описание рецепта')),
                ('cooking_time', models.IntegerField(help_text='Введите время приготовления в минутах', verbose_name='Время приготовления')),
                ('is_favorited', models.BooleanField(default=False, help_text='Указывает, добавил ли текущий пользователь рецепт в избранное', verbose_name='Добавлен в избранное')),
                ('short_link', models.CharField(blank=True, help_text='Короткая ссылка на рецепт', max_length=255, verbose_name='Короткая ссылка')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название тега', max_length=255, unique=True, verbose_name='Название тега')),
                ('slug', models.SlugField(help_text='Введите slug тега', unique=True, verbose_name='Slug тега')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipes', models.ManyToManyField(help_text='Выберите рецепты для корзины', to='recipes.Recipe', verbose_name='Рецепты')),
            ],
        ),
    ]
